---
- name: Create Project in Ansible AWX
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Create project in AWX
      uri:
        url: "https://your-awx-server/api/v2/projects/"
        method: POST
        headers:
          Authorization: "Bearer ZhtfS0YyN5zzKMCQXdtvLua8JiV9hA"
        body:
          name: "my_project"
          description: "This is my project created via Ansible"
          scm_type: "git"
          scm_url: "https://github.com/your-repo/project.git"
          scm_branch: "main"
        body_format: json
        return_content: yes
      register: result

    - name: Debug the result
      debug:
        var: result
